version: '3'
services:
  server1:
    build: ./server1
    ports:
    - "5001:80"
  server2:
    build: ./server2
    ports:
    - "5002:80"
  server3:
    build: ./server3
    ports:
    - "5003:80"
  nginx:
    build: ./gateway
    ports:
    - "8080:80"
    depends_on:
      - server1
      - server2
      - server3
